[package]
name = "probl-syntax"
description = "Internal to Probl, with no stable API: its lexer, parser, AST and diagnostics. Use the `probl` crate."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
probl-number.workspace = true
ariadne.workspace = true

[dev-dependencies]
insta.workspace = true
