[package]
name = "probl-cli"
description = "The probl command-line tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true

[[bin]]
name = "probl"
path = "src/main.rs"

[dependencies]
probl.workspace = true
probl-syntax.workspace = true
probl-sema.workspace = true
probl-engine.workspace = true
clap.workspace = true

[dev-dependencies]
libtest-mimic.workspace = true

[[test]]
name = "examples"
harness = false
