[package]
name = "probl-sema"
description = "Internal to Probl, with no stable API: name resolution, lowering to IR and liveness analysis. Use the `probl` crate."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
probl-number.workspace = true
probl-syntax.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
insta.workspace = true
